# This is a basic workflow to help you get started with Actions

name: CI


on:

  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

                  
          
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      
